name: deploy-log
on:
  pull_request:
    types:
      - closed

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Get last merge comment
          env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          run: |
                PR_NUMBER=${{ github.event.pull_request.number }}
                COMMENTS_URL=${{ github.event.pull_request.comments_url }}
                chmod +x ./.github/script.sh
                ./.github/script.sh